GET {{url}}/one-short-description
content-type: application/json

{
    "query": "https://lifehacker.ru/oshibki-pri-uborke-pylesosom/"
}

###
GET {{url}}/one-short-description
content-type: application/json

{
    "query": "Еда - это не просто средство насыщения организма, а целый мир вкусов и ароматов. Она способна радовать нас не только физически, но и эмоционально. В каждом блюде заложена частичка тепла и заботы тех, кто его готовил. Приготовление еды - это настоящее искусство, которое позволяет нам выразить свою любовь и заботу к близким. Кулинария объединяет людей и создает атмосферу уюта и радости. Вкусная еда - это нечто большее, чем просто продукты, это наш способ понимания и выражения себя."
}

### fake url
GET {{url}}/one-short-description
content-type: application/json

{
    "query": "https://www.elle.ru/krasota/uhod-za-kozhey/10-samyh-populyarnyh-kremov-dlya-lica/"
}