GET {{url}}/one-short-description
content-type: application/json

{
    "query": "https://eu.usatoday.com/story/graphics/2024/06/26/trump-vp-choices-pros-cons/74186580007/"
}

### text
GET {{url}}/one-short-description
content-type: application/json

{
    "query": "Еда - это не просто средство насыщения организма, а целый мир вкусов и ароматов. Она способна радовать нас не только физически, но и эмоционально. В каждом блюде заложена частичка тепла и заботы тех, кто его готовил. Приготовление еды - это настоящее искусство, которое позволяет нам выразить свою любовь и заботу к близким. Кулинария объединяет людей и создает атмосферу уюта и радости. Вкусная еда - это нечто большее, чем просто продукты, это наш способ понимания и выражения себя."
}

### fake url
GET {{url}}/one-short-description
content-type: application/json

{
    "query": "https://www.elle.ru/krasota/uhod-za-kozhey/10-samyh-populyarnyh-kremov-dlya-lica/"
}

### all short descriptions
GET {{url}}/all-short-descriptions
content-type: application/json

{
    "query": ["https://lifehacker.ru/kitae-ispytali-vertikalnuyu-posadku-rakety/", "https://lifehacker.ru/33-grobnicy-s-neobychnymi-mumiyami/", "https://lifehacker.ru/predstavlena-kolonka-beats-pill/"]
}